### ISSUE TITLE
What is this code licensed under?

### ISSUE THREAD

**Issue by psteinb** [jonbarron/hist_thresh#3]
I don't see any hint on licensing. Could you please share under which conditions we can reuse, share or extend the code?

**Comment by jonbarron** [comment]
experiments.ipynb and interactive_viewer have Apache 2 licenses at the head, the .R file was submitted without a license.

**Comment by psteinb** [comment]
ah, didn't even check that. thanks for pointing that out. I am so used to repos yielding a LICENSE.md or alike.
